### ISSUE TITLE
pickle files

### ISSUE THREAD

**Issue by nastaran75** [learningtitans/isbi2017-part3#3]
I cannot find "classes_to_sizes.pkl" and "splits_to_sizes.pkl". Can you upload them or tell me what I should put in those files please?

Thank you for sharing your code :)

**Comment by dreavjr** [comment]
Hi nastaran75, you are welcome. :-)

I assume that — since you closed the issue yourself — you found the files? For recording purposes: they are generated by the script datasets/convert_skin_lesions.py and are in the same directory as the .tfr files created. Let me know if you need further info.

**Comment by nastaran75** [comment]
Dear Eduardo, 
Yes I generated the files. Thank you :)
Really appreciate you taking time to answer the issues :)
Regards
