### ISSUE TITLE
more than 3 channels input

### ISSUE THREAD

**Issue by nastaran75** [learningtitans/isbi2017-part3#5]
Dear Eduardo Valle,
I want to use your model for a different task with some images which are not 3-channel images (more than 3). I am trying to make tf records of my data by changing the convert_skin_lesion.py file. Do you think it is possible?

Thanks

**Comment by dreavjr** [comment]
Hmmm... it depends: if you want to simply convert your multi-spectral images to 3-channels and then feed them to the model, I'd think your plan would work. If you want to feed n-channels to the models, there are several modifications that need to be made: the conversion, of course, but also, the database/.py files, and — most challenging — the models themselves. You would have to modify the input layer of all models to accept n channels (and that would mess up all attempts of transfer learning).

If you do succeed in doing it, send my a ping — I'll be very interested in studying your solution.
