### ISSUE TITLE
PyTorch Pretrained Model

### ISSUE THREAD

**Issue by Taha-Bahadori** [learningtitans/isbi2017-part3#8]
I found this repo very helpful, with nice documentation!

Would it be possible to help me with converting the pretrained model to PyTorch?

**Comment by dreavjr** [comment]
Hi ! Converting Slim to PyTorch would be extremely challenging. May I suggest that you take a look at out 2018 participation instead? The models we submitted that year were in PyTorch: https://github.com/learningtitans/isic2018-part3 / https://arxiv.org/abs/1808.08480

**Comment by Taha-Bahadori** [comment]
@dreavjr 
Thank you. This is helpful. I wish you had put this link in the beginning of this repo's README file.

**Comment by Taha-Bahadori** [comment]
@dreavjr Do you make the pretrained PyTorch model available?
